import './globals.css'
import { Ubuntu } from 'next/font/google'

const inter = Ubuntu({ weight: ['400'], subsets: ['latin'] })

export const metadata = {
  title: 'Summary page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
